-- Phase 2 — helper functions, triggers, and business RPCs.
-- Hand-written (not Drizzle-generated) per architecture §3: "RLS policies
-- and Postgres functions ... versioned alongside migrations, not
-- generated by Drizzle." Every SECURITY DEFINER function below sets an
-- explicit search_path (Postgres search-path-hijacking hardening) and is
-- the ONLY writer for the tables it touches — see 0002_rls_policies.sql,
-- which grants no direct INSERT/UPDATE/DELETE to `authenticated`/`anon`
-- on the orders family at all (Finding 6).

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- staff_users <-> auth.users
-- ============================================================
-- staff_users "mirrors auth.users 1:1" (§7). The FK and the mirroring
-- trigger both reference auth.users, which Supabase already provides in
-- every real project — this statement is a no-op requirement there, but
-- our local Postgres test harness must create an equivalent auth.users
-- table before this migration can apply (see db/testing/harness.sql).
ALTER TABLE "staff_users"
  ADD CONSTRAINT "staff_users_id_auth_users_fk"
  FOREIGN KEY ("id") REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.staff_users (id, email, full_name)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data ->> 'full_name', '')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_auth_user();

-- ============================================================
-- updated_at maintenance
-- ============================================================
-- DB-level, not app-level, so it holds even if a server action forgets
-- to set it — "the database must remain safe even if the application
-- layer contains a bug."
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_restaurants_set_updated_at
  BEFORE UPDATE ON "restaurants"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_tables_set_updated_at
  BEFORE UPDATE ON "tables"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_menu_items_set_updated_at
  BEFORE UPDATE ON "menu_items"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_orders_set_updated_at
  BEFORE UPDATE ON "orders"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- RLS helper functions
-- ============================================================
-- SECURITY DEFINER + STABLE, per Supabase's own documented pattern for
-- RLS helpers: they must bypass RLS on restaurant_staff internally (via
-- definer rights) to avoid recursive policy evaluation when
-- restaurant_staff's own policies call them.

CREATE OR REPLACE FUNCTION public.is_staff_of(p_restaurant_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM restaurant_staff
    WHERE restaurant_id = p_restaurant_id
      AND staff_user_id = auth.uid()
      AND is_active = true
  );
$$;

CREATE OR REPLACE FUNCTION public.staff_role_for(p_restaurant_id uuid)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role::text FROM restaurant_staff
  WHERE restaurant_id = p_restaurant_id
    AND staff_user_id = auth.uid()
    AND is_active = true
  LIMIT 1;
$$;

-- Mirrors lib/business/orderStateMachine.ts::canTransition exactly (§15).
-- Kept in sync by hand — see the comment in that file.
CREATE OR REPLACE FUNCTION public.is_legal_order_transition(p_from text, p_to text, p_role text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT p_from <> p_to
    AND p_from NOT IN ('completed', 'cancelled')
    AND (
      (p_from = 'new'       AND p_to = 'preparing' AND p_role IN ('admin', 'staff')) OR
      (p_from = 'new'       AND p_to = 'cancelled' AND p_role IN ('admin', 'staff')) OR
      (p_from = 'preparing' AND p_to = 'ready'     AND p_role IN ('admin', 'staff')) OR
      (p_from = 'preparing' AND p_to = 'new'       AND p_role IN ('admin', 'staff')) OR
      (p_from = 'preparing' AND p_to = 'cancelled' AND p_role IN ('admin', 'staff')) OR
      (p_from = 'ready'     AND p_to = 'completed' AND p_role IN ('admin', 'staff')) OR
      (p_from = 'ready'     AND p_to = 'cancelled' AND p_role = 'admin')
    );
$$;

-- Finding 4: atomic per-restaurant, per-day order numbering. One
-- statement, so two concurrent callers serialize on the same
-- (restaurant_id, day) row instead of racing.
CREATE OR REPLACE FUNCTION public.next_order_number(p_restaurant_id uuid)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_day date := current_date;
  v_count int;
  v_prefix text;
BEGIN
  INSERT INTO restaurant_daily_counters (restaurant_id, day, counter)
  VALUES (p_restaurant_id, v_day, 1)
  ON CONFLICT (restaurant_id, day)
  DO UPDATE SET counter = restaurant_daily_counters.counter + 1
  RETURNING counter INTO v_count;

  SELECT order_number_prefix INTO v_prefix
  FROM restaurant_settings WHERE restaurant_id = p_restaurant_id;

  RETURN COALESCE(v_prefix, 'A') || '-' || lpad(v_count::text, 3, '0');
END;
$$;

-- §21's toggleItemAvailability contract: staff (any role) may flip
-- is_available; only admin may change anything else about a menu item.
-- RLS (0002) allows any staff to attempt the UPDATE at the row level;
-- this trigger is the column-level enforcement RLS alone can't express.
CREATE OR REPLACE FUNCTION public.enforce_menu_item_update_scope()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.staff_role_for(NEW.restaurant_id) = 'admin' THEN
    RETURN NEW;
  END IF;

  IF NEW.name IS DISTINCT FROM OLD.name
     OR NEW.slug IS DISTINCT FROM OLD.slug
     OR NEW.description IS DISTINCT FROM OLD.description
     OR NEW.short_description IS DISTINCT FROM OLD.short_description
     OR NEW.price_cents IS DISTINCT FROM OLD.price_cents
     OR NEW.category_id IS DISTINCT FROM OLD.category_id
     OR NEW.image_url IS DISTINCT FROM OLD.image_url
     OR NEW.ingredients IS DISTINCT FROM OLD.ingredients
     OR NEW.allergens IS DISTINCT FROM OLD.allergens
     OR NEW.prep_time_minutes IS DISTINCT FROM OLD.prep_time_minutes
     OR NEW.is_active IS DISTINCT FROM OLD.is_active
     OR NEW.is_featured IS DISTINCT FROM OLD.is_featured
     OR NEW.sort_order IS DISTINCT FROM OLD.sort_order
  THEN
    RAISE EXCEPTION 'FORBIDDEN: only admin may edit this field; staff may only toggle availability'
      USING ERRCODE = 'P0020';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_menu_items_update_scope
  BEFORE UPDATE ON "menu_items"
  FOR EACH ROW EXECUTE FUNCTION public.enforce_menu_item_update_scope();

-- ============================================================
-- Audit logging foundation (§29) — table + helper only in Phase 2.
-- Nothing calls this yet; see the note in lib/db/schema/orders.ts.
-- ============================================================
CREATE OR REPLACE FUNCTION public.log_audit_event(
  p_restaurant_id uuid,
  p_action text,
  p_entity_type text,
  p_entity_id uuid,
  p_previous_value jsonb DEFAULT NULL,
  p_new_value jsonb DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id uuid;
BEGIN
  INSERT INTO audit_logs (restaurant_id, actor_staff_id, action, entity_type, entity_id, previous_value, new_value)
  VALUES (p_restaurant_id, auth.uid(), p_action, p_entity_type, p_entity_id, p_previous_value, p_new_value)
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

-- ============================================================
-- resolve_table_by_token — §12/§21 resolveTable(token)
-- ============================================================
-- table_qr_tokens has no anon grant at all (0002) — this is the only way
-- a QR scan resolves to a table, and it never exposes the raw token list.
CREATE OR REPLACE FUNCTION public.resolve_table_by_token(p_token text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row record;
BEGIN
  SELECT
    t.id AS table_id, t.label AS table_label, t.is_active AS table_active,
    r.id AS restaurant_id, r.name AS restaurant_name, r.is_active AS restaurant_active,
    r.ordering_enabled, r.currency
  INTO v_row
  FROM table_qr_tokens qt
  JOIN tables t ON t.id = qt.table_id
  JOIN restaurants r ON r.id = t.restaurant_id
  WHERE qt.token = p_token AND qt.is_active = true;

  IF v_row.table_id IS NULL THEN
    RAISE EXCEPTION 'INVALID_TOKEN' USING ERRCODE = 'P0014';
  END IF;

  RETURN jsonb_build_object(
    'table_id', v_row.table_id,
    'table_label', v_row.table_label,
    'table_active', v_row.table_active,
    'restaurant_id', v_row.restaurant_id,
    'restaurant_name', v_row.restaurant_name,
    'restaurant_active', v_row.restaurant_active,
    'ordering_enabled', v_row.ordering_enabled,
    'currency', v_row.currency
  );
END;
$$;

-- ============================================================
-- create_order — §9/§26 order-creation guarantee
-- ============================================================
-- Two passes over p_items: pass 1 validates + prices everything and locks
-- the priced rows (FOR SHARE, held for the rest of the transaction) before
-- the parent `orders` row exists; pass 2 inserts order_items/
-- order_item_options against the now-locked, already-validated rows. This
-- ordering exists because order_items.order_id can't reference an orders
-- row that doesn't exist yet, and the parent row's total_cents (checked
-- by orders_total_equals_components) must be known before it's inserted.
CREATE OR REPLACE FUNCTION public.create_order(
  p_table_id uuid,
  p_items jsonb,           -- [{menu_item_id, quantity, option_choice_ids: [uuid,...], line_note}]
  p_customer_note text,
  p_idempotency_key text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_restaurant_id uuid;
  v_table_active boolean;
  v_ordering_enabled boolean;
  v_existing record;
  v_session_id uuid;
  v_order_id uuid;
  v_access_token text;
  v_order_number text;
  v_subtotal bigint := 0;
  v_line_subtotal bigint;
  v_tax_rate numeric;
  v_service_rate numeric;
  v_tax_cents bigint;
  v_service_cents bigint;
  v_total_cents bigint;
  v_item jsonb;
  v_choice_id uuid;
  v_menu_item record;
  v_choice record;
  v_order_item_id uuid;
  v_qty int;
BEGIN
  IF p_idempotency_key IS NULL OR length(p_idempotency_key) = 0 THEN
    RAISE EXCEPTION 'MISSING_IDEMPOTENCY_KEY' USING ERRCODE = 'P0021';
  END IF;

  -- Finding 4 / edge cases 6+7: retried or double-tapped submit resolves
  -- to the original order instead of creating a second one.
  SELECT id, order_number, access_token, total_cents INTO v_existing
  FROM orders WHERE idempotency_key = p_idempotency_key;

  IF FOUND THEN
    RETURN jsonb_build_object(
      'order_id', v_existing.id,
      'order_number', v_existing.order_number,
      'access_token', v_existing.access_token,
      'total_cents', v_existing.total_cents
    );
  END IF;

  SELECT t.restaurant_id, t.is_active, r.ordering_enabled
  INTO v_restaurant_id, v_table_active, v_ordering_enabled
  FROM tables t JOIN restaurants r ON r.id = t.restaurant_id
  WHERE t.id = p_table_id;

  IF v_restaurant_id IS NULL THEN
    RAISE EXCEPTION 'TABLE_NOT_FOUND' USING ERRCODE = 'P0000';
  END IF;
  IF NOT v_table_active THEN
    RAISE EXCEPTION 'TABLE_INACTIVE' USING ERRCODE = 'P0001';
  END IF;
  IF NOT v_ordering_enabled THEN
    RAISE EXCEPTION 'ORDERING_DISABLED' USING ERRCODE = 'P0002';
  END IF;

  IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'EMPTY_ORDER' USING ERRCODE = 'P0003';
  END IF;

  -- Pass 1: validate + price. FOR SHARE locks are held for the rest of
  -- this transaction, so pass 2 below is guaranteed to see the same rows.
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_qty := (v_item ->> 'quantity')::int;
    IF v_qty IS NULL OR v_qty < 1 OR v_qty > 20 THEN
      RAISE EXCEPTION 'INVALID_QUANTITY' USING ERRCODE = 'P0004';
    END IF;

    SELECT id, name, price_cents, is_active, is_available
    INTO v_menu_item
    FROM menu_items
    WHERE id = (v_item ->> 'menu_item_id')::uuid
      AND restaurant_id = v_restaurant_id
    FOR SHARE;

    IF v_menu_item.id IS NULL THEN
      RAISE EXCEPTION 'MENU_ITEM_NOT_FOUND' USING ERRCODE = 'P0005';
    END IF;
    IF NOT v_menu_item.is_active OR NOT v_menu_item.is_available THEN
      RAISE EXCEPTION 'MENU_ITEM_UNAVAILABLE: %', v_menu_item.name USING ERRCODE = 'P0006';
    END IF;

    v_line_subtotal := v_menu_item.price_cents * v_qty;

    FOR v_choice_id IN
      SELECT jsonb_array_elements_text(COALESCE(v_item -> 'option_choice_ids', '[]'::jsonb))::uuid
    LOOP
      SELECT oc.id, oc.name, oc.price_delta_cents, oc.is_available
      INTO v_choice
      FROM option_choices oc
      JOIN option_groups og ON og.id = oc.option_group_id
      WHERE oc.id = v_choice_id
        AND og.menu_item_id = v_menu_item.id
        AND oc.restaurant_id = v_restaurant_id
      FOR SHARE;

      IF v_choice.id IS NULL THEN
        RAISE EXCEPTION 'OPTION_NOT_FOUND' USING ERRCODE = 'P0007';
      END IF;
      IF NOT v_choice.is_available THEN
        RAISE EXCEPTION 'OPTION_UNAVAILABLE: %', v_choice.name USING ERRCODE = 'P0008';
      END IF;

      v_line_subtotal := v_line_subtotal + (v_choice.price_delta_cents * v_qty);
    END LOOP;

    v_subtotal := v_subtotal + v_line_subtotal;
  END LOOP;

  SELECT tax_rate, service_charge_rate INTO v_tax_rate, v_service_rate
  FROM restaurant_settings WHERE restaurant_id = v_restaurant_id;

  v_tax_cents := round(v_subtotal * COALESCE(v_tax_rate, 0));
  v_service_cents := round(v_subtotal * COALESCE(v_service_rate, 0));
  v_total_cents := v_subtotal + v_tax_cents + v_service_cents;

  -- Finding 1: race-safe session acquisition. Reuses the table's open
  -- session if one exists; otherwise this INSERT wins the race against
  -- any concurrent caller doing the same thing for the same table.
  INSERT INTO table_sessions (restaurant_id, table_id, status)
  VALUES (v_restaurant_id, p_table_id, 'open')
  ON CONFLICT (table_id) WHERE status = 'open' DO NOTHING
  RETURNING id INTO v_session_id;

  IF v_session_id IS NULL THEN
    SELECT id INTO v_session_id FROM table_sessions
    WHERE table_id = p_table_id AND status = 'open';
  END IF;

  v_order_number := public.next_order_number(v_restaurant_id);
  v_access_token := encode(gen_random_bytes(24), 'hex');
  v_order_id := gen_random_uuid();

  INSERT INTO orders (
    id, restaurant_id, table_id, table_session_id, order_number, status,
    subtotal_cents, tax_cents, service_charge_cents, total_cents,
    customer_note, access_token, idempotency_key
  ) VALUES (
    v_order_id, v_restaurant_id, p_table_id, v_session_id, v_order_number, 'new',
    v_subtotal, v_tax_cents, v_service_cents, v_total_cents,
    p_customer_note, v_access_token, p_idempotency_key
  );

  -- Pass 2: insert line items against the now-existing order, re-reading
  -- the exact rows locked in pass 1 (still locked — same transaction).
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_qty := (v_item ->> 'quantity')::int;

    SELECT id, name, price_cents
    INTO v_menu_item
    FROM menu_items WHERE id = (v_item ->> 'menu_item_id')::uuid;

    INSERT INTO order_items (
      restaurant_id, order_id, menu_item_id, name_snapshot, unit_price_cents_snapshot, quantity, line_note
    ) VALUES (
      v_restaurant_id, v_order_id, v_menu_item.id, v_menu_item.name, v_menu_item.price_cents, v_qty,
      v_item ->> 'line_note'
    )
    RETURNING id INTO v_order_item_id;

    FOR v_choice_id IN
      SELECT jsonb_array_elements_text(COALESCE(v_item -> 'option_choice_ids', '[]'::jsonb))::uuid
    LOOP
      SELECT oc.name, oc.price_delta_cents, og.name AS group_name
      INTO v_choice
      FROM option_choices oc
      JOIN option_groups og ON og.id = oc.option_group_id
      WHERE oc.id = v_choice_id;

      INSERT INTO order_item_options (
        restaurant_id, order_item_id, group_name_snapshot, choice_name_snapshot, price_delta_cents_snapshot
      ) VALUES (
        v_restaurant_id, v_order_item_id, v_choice.group_name, v_choice.name, v_choice.price_delta_cents
      );
    END LOOP;
  END LOOP;

  INSERT INTO order_status_history (restaurant_id, order_id, previous_status, new_status, changed_by_staff_id, note)
  VALUES (v_restaurant_id, v_order_id, NULL, 'new', NULL, NULL);

  RETURN jsonb_build_object(
    'order_id', v_order_id,
    'order_number', v_order_number,
    'access_token', v_access_token,
    'total_cents', v_total_cents
  );
END;
$$;

-- ============================================================
-- set_order_status — §15/§21 setOrderStatus, Findings 2 & 3
-- ============================================================
CREATE OR REPLACE FUNCTION public.set_order_status(
  p_order_id uuid,
  p_new_status text,
  p_note text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order record;
  v_role text;
  v_remaining_active int;
BEGIN
  -- Finding 3: lock the row before validating. A concurrent second call
  -- blocks here until this transaction commits, then re-validates against
  -- whatever actually landed — never a silent overwrite.
  SELECT * INTO v_order FROM orders WHERE id = p_order_id FOR UPDATE;

  IF v_order.id IS NULL THEN
    RAISE EXCEPTION 'ORDER_NOT_FOUND' USING ERRCODE = 'P0010';
  END IF;

  v_role := public.staff_role_for(v_order.restaurant_id);
  IF v_role IS NULL THEN
    RAISE EXCEPTION 'FORBIDDEN' USING ERRCODE = 'P0011';
  END IF;

  IF NOT public.is_legal_order_transition(v_order.status::text, p_new_status, v_role) THEN
    RAISE EXCEPTION 'ILLEGAL_TRANSITION: % -> % (role %)', v_order.status, p_new_status, v_role
      USING ERRCODE = 'P0012';
  END IF;

  UPDATE orders SET status = p_new_status::order_status WHERE id = p_order_id;

  INSERT INTO order_status_history (restaurant_id, order_id, previous_status, new_status, changed_by_staff_id, note)
  VALUES (v_order.restaurant_id, p_order_id, v_order.status::text, p_new_status, auth.uid(), p_note);

  -- Finding 2: auto-close the session the instant it has zero
  -- non-terminal orders left. closed_by_staff_id stays NULL to mark this
  -- as an auto-close, distinct from a manual "clear table".
  IF p_new_status IN ('completed', 'cancelled') THEN
    SELECT count(*) INTO v_remaining_active
    FROM orders
    WHERE table_session_id = v_order.table_session_id
      AND status NOT IN ('completed', 'cancelled');

    IF v_remaining_active = 0 THEN
      UPDATE table_sessions
      SET status = 'closed', closed_at = now(), closed_by_staff_id = NULL
      WHERE id = v_order.table_session_id AND status = 'open';
    END IF;
  END IF;

  RETURN jsonb_build_object('order_id', p_order_id, 'status', p_new_status);
END;
$$;

-- ============================================================
-- clear_table — §18 manual session-close override
-- ============================================================
CREATE OR REPLACE FUNCTION public.clear_table(p_table_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_restaurant_id uuid;
  v_role text;
BEGIN
  SELECT restaurant_id INTO v_restaurant_id FROM tables WHERE id = p_table_id;
  IF v_restaurant_id IS NULL THEN
    RAISE EXCEPTION 'TABLE_NOT_FOUND' USING ERRCODE = 'P0015';
  END IF;

  v_role := public.staff_role_for(v_restaurant_id);
  IF v_role IS NULL THEN
    RAISE EXCEPTION 'FORBIDDEN' USING ERRCODE = 'P0016';
  END IF;

  UPDATE table_sessions
  SET status = 'closed', closed_at = now(), closed_by_staff_id = auth.uid()
  WHERE table_id = p_table_id AND status = 'open';
END;
$$;

-- ============================================================
-- get_order_by_token — §13/§21/§26 anonymous order tracking
-- ============================================================
-- Deliberately excludes changed_by_staff_id from the status timeline —
-- same "minimal payload, no staff identity" principle as the realtime
-- broadcast (§16, §27).
CREATE OR REPLACE FUNCTION public.get_order_by_token(p_access_token text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order record;
  v_items jsonb;
  v_history jsonb;
BEGIN
  SELECT
    o.id, o.order_number, o.status, o.subtotal_cents, o.tax_cents, o.service_charge_cents,
    o.total_cents, o.customer_note, o.created_at, t.label AS table_label
  INTO v_order
  FROM orders o JOIN tables t ON t.id = o.table_id
  WHERE o.access_token = p_access_token;

  IF v_order.id IS NULL THEN
    RAISE EXCEPTION 'ORDER_NOT_FOUND' USING ERRCODE = 'P0013';
  END IF;

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'name', oi.name_snapshot,
    'unit_price_cents', oi.unit_price_cents_snapshot,
    'quantity', oi.quantity,
    'line_note', oi.line_note,
    'options', (
      SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'group', oo.group_name_snapshot,
        'choice', oo.choice_name_snapshot,
        'price_delta_cents', oo.price_delta_cents_snapshot
      )), '[]'::jsonb)
      FROM order_item_options oo WHERE oo.order_item_id = oi.id
    )
  )), '[]'::jsonb) INTO v_items
  FROM order_items oi WHERE oi.order_id = v_order.id;

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'previous_status', h.previous_status,
    'new_status', h.new_status,
    'created_at', h.created_at
  ) ORDER BY h.created_at), '[]'::jsonb) INTO v_history
  FROM order_status_history h WHERE h.order_id = v_order.id;

  RETURN jsonb_build_object(
    'order_number', v_order.order_number,
    'status', v_order.status,
    'table_label', v_order.table_label,
    'subtotal_cents', v_order.subtotal_cents,
    'tax_cents', v_order.tax_cents,
    'service_charge_cents', v_order.service_charge_cents,
    'total_cents', v_order.total_cents,
    'customer_note', v_order.customer_note,
    'created_at', v_order.created_at,
    'items', v_items,
    'status_history', v_history
  );
END;
$$;
